from django.contrib import admin
from core.models import (Apartamentos, Abastecimentos, AberturasPortas, AcessosApp, AgendamentoHorarios,
Agendamentos, Areas, AreasParalelas, Atendimentos, Atividades, AtividadesMateriaisProdutos, AtividadesOrdemdeservicos,
AuthGroup, AuthGroupPermissions, AuthPermission, AuthUser, AuthUserGroups, AuthUserUserPermissions, CamFacials,
CardsElevadors, CentraisJfls, Chamadas, ChavesVirtuais, ChecklistObras, Codigos, ComercialEtapas, ComercialLeadEtapas,
ComercialLeadProcessos, ComercialLeads, ComercialProcessos, ComercialProspeccao, Comodatos,CondominioEquipamentos,
Condominios, CondominiosFeriados, CondominiosFuncionarios, CondominiosFuncionariosDispositivosRoles, ConfigFacials,
ConfigOs, ContatoEmergencias, ControlesAcessos, Convidados, Criticidades, Departamentos, Dispositivos, DispositivosAcessos,
DispositivosCards, DispositivosCardsTipos, DispositivosEventos, DispositivosMarcas,DispositivosModelos, DispositivosRegistros,
DispositivosRoles, DispositivosRolesDispositivosAcessos, DispositivosTipos, DjangoAdminLog, DjangoContentType,DjangoMigrations,
DjangoSession, Documentos, ElevadorChamados, Empresas, EmpresasServicos, EmpresasServicosEmpresas, Encomendas,
EntregadoresNormas, EstadosEquipamentos, Eventos, EventosTratados,Faturamentos, FaturamentosMateriais,FaturamentosOrcamentos,
Feriados, Ferramentas, Fotos, Funcionarios, GruposEventos, GruposZonas, HistoricoCondominios, HistoricoPessoas, Imagemcameras,
Informativos, Internets, ItensCadastrados, ItensOrcamentos, ItensVistorias, LiberacoesAcessos, LiberacoesChaves, MateriaisAtividades,
MateriaisGrupos, MateriaisMarcas, MateriaisObras, MateriaisProdutos, MateriaisUnidades, MudancasNormas, Notificacoes, Obras,
ObrasChecklistObras, Ocorrencias, Orcamentos, OrcamentosMateriais, OrcamentosPessoas, Ordemdeservicos, OrdemdeservicosMateriaisProdutos,
Parcelas, Patrimonios, Pedagios, PermissaoAcessos, PermissaoAcessosDispositivosRoles, Pessoas, PessoasDispositivosRoles, Pets,
Pgms, PlantaoOcorrencias, PlantaoOperacionals, Portas, PrestadoresAcessos, PrestadoresNormas, Projetos, Qths, QthsTarefas,
QthsTarefasQths, Questionarios, Racas, Recados, ReconhecidoFacials, ReservasNormas, Roles, Sindicos, Subramais, SubtiposOcorrencias,
SubtiposOcorrenciasOcorrencias, SubtiposTiposAbastecimentos, Suporteunidades, Tarefas, TatticaFuncionarios, TatticaTelefones,
TatticaVeiculos, TiposAbastecimentos, TiposAcessos, TiposClassificacaos, TiposCondominiosFuncionarios,TiposControlesAcessos,
TiposElevadorChamados, TiposEncomendas, TiposEquipamentos, TiposEventosTratados, TiposFotos, TiposFuncionarios, TiposOcorrencias,
TiposOcorrenciasOcorrencias, TiposPagamentos, TiposPatrimonios, TiposPedagios, TiposPessoas, TiposProjetos, TiposRacas,
TiposSindicos, TiposTarefas, TiposVeiculos, TiposZonas, Tips, TipsTatticaFuncionarios, Unidades, Users, Vagas,Veiculos,
Vistorias, VistoriasItensVistorias, Zonas)

admin.site.register(Apartamentos)
admin.site.register(Abastecimentos)
admin.site.register(AberturasPortas)
admin.site.register(AcessosApp)
admin.site.register(AgendamentoHorarios)
admin.site.register(Agendamentos)
admin.site.register(Areas)
admin.site.register(AreasParalelas)
admin.site.register(Atendimentos)
admin.site.register(Atividades)
admin.site.register(AtividadesMateriaisProdutos)
admin.site.register(AtividadesOrdemdeservicos)
admin.site.register(AuthGroup)
admin.site.register(AuthPermission)
admin.site.register(AuthGroupPermissions)
admin.site.register(AuthUser)
admin.site.register(AuthUserGroups)
admin.site.register(AuthUserUserPermissions)
admin.site.register(CamFacials)
admin.site.register(CardsElevadors)
admin.site.register(CentraisJfls)
admin.site.register(Chamadas)
admin.site.register(ChavesVirtuais)
admin.site.register(ChecklistObras)
admin.site.register(Codigos)
admin.site.register(ComercialEtapas)
admin.site.register(ComercialLeadEtapas)
admin.site.register(ComercialLeadProcessos)
admin.site.register(ComercialLeads)
admin.site.register(ComercialProcessos)
admin.site.register(ComercialProspeccao)
admin.site.register(Comodatos)
admin.site.register(CondominioEquipamentos)
admin.site.register(Condominios)
admin.site.register(CondominiosFeriados)
admin.site.register(CondominiosFuncionarios)
admin.site.register(CondominiosFuncionariosDispositivosRoles)
admin.site.register(ConfigFacials)
admin.site.register(ConfigOs)
admin.site.register(ContatoEmergencias)
admin.site.register(ControlesAcessos)
admin.site.register(Convidados)
admin.site.register(Criticidades)
admin.site.register(Departamentos)
admin.site.register(Dispositivos)
admin.site.register(DispositivosAcessos)
admin.site.register(DispositivosCards)
admin.site.register(DispositivosCardsTipos)
admin.site.register(DispositivosEventos)
admin.site.register(DispositivosMarcas)
admin.site.register(DispositivosModelos)
admin.site.register(DispositivosRegistros)
admin.site.register(DispositivosRoles)
admin.site.register(DispositivosRolesDispositivosAcessos)
admin.site.register(DispositivosTipos)
admin.site.register(DjangoAdminLog)
admin.site.register(DjangoContentType)
admin.site.register(DjangoMigrations)
admin.site.register(DjangoSession)
admin.site.register(Documentos)
admin.site.register(ElevadorChamados)
admin.site.register(Empresas)
admin.site.register(EmpresasServicos)
admin.site.register(EmpresasServicosEmpresas)
admin.site.register(Encomendas)
admin.site.register(EntregadoresNormas)
admin.site.register(EstadosEquipamentos)
admin.site.register(Eventos)
admin.site.register(EventosTratados)
admin.site.register(Faturamentos)
admin.site.register(FaturamentosMateriais)
admin.site.register(FaturamentosOrcamentos)
admin.site.register(Feriados)
admin.site.register(Ferramentas)
admin.site.register(Fotos)
admin.site.register(Funcionarios)
admin.site.register(GruposEventos)
admin.site.register(GruposZonas)
admin.site.register(HistoricoCondominios)
admin.site.register(HistoricoPessoas)
admin.site.register(Imagemcameras)
admin.site.register(Informativos)
admin.site.register(Internets)
admin.site.register(ItensCadastrados)
admin.site.register(ItensOrcamentos)
admin.site.register(ItensVistorias)
admin.site.register(LiberacoesAcessos)
admin.site.register(LiberacoesChaves)
admin.site.register(MateriaisAtividades)
admin.site.register(MateriaisGrupos)
admin.site.register(MateriaisMarcas)
admin.site.register(MateriaisObras)
admin.site.register(MateriaisProdutos)
admin.site.register(MateriaisUnidades)
admin.site.register(MudancasNormas)
admin.site.register(Notificacoes)
admin.site.register(Obras)
admin.site.register(ObrasChecklistObras)
admin.site.register(Ocorrencias)
admin.site.register(Orcamentos)
admin.site.register(OrcamentosMateriais)
admin.site.register(OrcamentosPessoas)
admin.site.register(Ordemdeservicos)
admin.site.register(OrdemdeservicosMateriaisProdutos)
admin.site.register(Parcelas)
admin.site.register(Patrimonios)
admin.site.register(Pedagios)
admin.site.register(PermissaoAcessos)
admin.site.register(PermissaoAcessosDispositivosRoles)
admin.site.register(Pessoas)
admin.site.register(PessoasDispositivosRoles)
admin.site.register(Pets)
admin.site.register(Pgms)
admin.site.register(PlantaoOcorrencias)
admin.site.register(PlantaoOperacionals)
admin.site.register(Portas)
admin.site.register(PrestadoresAcessos)
admin.site.register(PrestadoresNormas)
admin.site.register(Projetos)
admin.site.register(Qths)
admin.site.register(QthsTarefas)
admin.site.register(QthsTarefasQths)
admin.site.register(Questionarios)
admin.site.register(Racas)
admin.site.register(Recados)
admin.site.register(ReconhecidoFacials)
admin.site.register(ReservasNormas)
admin.site.register(Roles)
admin.site.register(Sindicos)
admin.site.register(Subramais)
admin.site.register(SubtiposOcorrencias)
admin.site.register(SubtiposOcorrenciasOcorrencias)
admin.site.register(SubtiposTiposAbastecimentos)
admin.site.register(Suporteunidades)
admin.site.register(Tarefas)
admin.site.register(TatticaFuncionarios)
admin.site.register(TatticaTelefones)
admin.site.register(TatticaVeiculos)
admin.site.register(TiposAbastecimentos)
admin.site.register(TiposAcessos)
admin.site.register(TiposClassificacaos)
admin.site.register(TiposCondominiosFuncionarios)
admin.site.register(TiposElevadorChamados)
admin.site.register(TiposEncomendas)
admin.site.register(TiposEquipamentos)
admin.site.register(TiposEventosTratados)
admin.site.register(TiposFotos)
admin.site.register(TiposFuncionarios)
admin.site.register(TiposOcorrencias)
admin.site.register(TiposOcorrenciasOcorrencias)
admin.site.register(TiposPagamentos)
admin.site.register(TiposPatrimonios)
admin.site.register(TiposPedagios)
admin.site.register(TiposPessoas)
admin.site.register(TiposProjetos)
admin.site.register(TiposRacas)
admin.site.register(TiposSindicos)
admin.site.register(TiposControlesAcessos)
admin.site.register(TiposTarefas)
admin.site.register(TiposVeiculos)
admin.site.register(TiposZonas)
admin.site.register(Tips)
admin.site.register(TipsTatticaFuncionarios)
admin.site.register(Unidades)
admin.site.register(Users)
admin.site.register(Vagas)
admin.site.register(Veiculos)
admin.site.register(Vistorias)
admin.site.register(VistoriasItensVistorias)
admin.site.register(Zonas)

